"""Catalyst map for FTAI's meaningful price moves.

dir:  up | down | mech (mechanical, not a value change)
conf: verified  - the move size is quoted by a source
      estimated - direction certain, size reconstructed from price anchors
      context   - catalyst inferred from macro/sector context, not a dated source
"""

ERAS = [
    dict(key="e1", start="2015-05-01", end="2019-12-31", file="01_2015-2019_infrastructure-era",
         title="2015 – 2019 · The Fortress holding-company years",
         sub="An externally managed grab-bag of aviation leasing, an oil terminal, a railroad and offshore vessels. "
             "It traded as a high-yield LLC (K-1 tax forms): its price was set by oil, credit spreads and dividend safety, not by aviation."),
    dict(key="e2", start="2020-01-01", end="2022-12-31", file="02_2020-2022_covid-russia-spin",
         title="2020 – 2022 · COVID, Russia, and splitting off the infrastructure assets",
         sub="Three shocks to the leasing book (COVID, then Russian sanctions, then rates). In the middle came the 2020 seed of the "
             "engine-module strategy, the 2022 spin-off of FTAI Infrastructure, and the conversion to a regular corporation."),
    dict(key="e3", start="2023-01-01", end="2024-12-31", file="03_2023-2024_aerospace-rerating",
         title="2023 – 2024 · Re-rated from aircraft lessor to aftermarket compounder",
         sub="The market stopped valuing FTAI as a lessor and started valuing Aerospace Products (CFM56 engine modules) as a "
             "high-margin aftermarket business. Guidance was raised again and again, and the stock rose ~10x."),
    dict(key="e4", start="2025-01-01", end="2025-12-31", file="04_2025_short-attack-and-recovery",
         title="2025 · Short-seller attack, audit review, and the comeback",
         sub="Two short sellers attacked the quality of Aerospace Products earnings. An independent review cleared FTAI. "
             "The stock then moved on beat/miss quality, and ended the year on a new data-center power business."),
    dict(key="e5", start="2026-01-01", end="2026-10-02", file="05_2026_power-hype-and-margin-reset",
         title="2026 · Power-turbine hype, then a margin and leasing reset",
         sub="The power-turbine business and an OEM truce drove an all-time high near $300. After that came an oil shock, "
             "four straight EPS misses, Aerospace margins guided down to ~30%, and a cut to leasing guidance."),
]

E = [
    # ======================= ERA 1 =======================
    dict(n=1, era="e1", date="2015-05-15", px=16.56, dir="down", move="−2.6% day 1 (IPO $17, below $19–21 range)", conf="verified",
         short="IPO prices below range",
         title="IPO: priced $2–4 below the range, then broke issue",
         what=["20.0M shares at $17.00 vs a $19–21 marketed range ($340M raised, down from a planned ~$400M).",
               "First close ≈ $16.56 (−2.6%).",
               "Assets: aviation leasing, Jefferson crude/products terminal (Beaumont TX), CMQR railroad, offshore energy vessels, shipping containers."],
         why="Buyers balked at an externally managed conglomerate. Fortress took a management fee, an incentive fee, and options on 10% "
             "of every future share issue. Half the asset base was early-stage, cash-burning infrastructure tied to the "
             "crude-by-rail boom, which was already rolling over."),
    dict(n=2, era="e1", date="2015-09-15", px=11.90, dir="down", move="≈ −37% ($18.90 → $11.83, Q3'15)", conf="context",
         short="Oil crash, 2nd leg",
         title="Summer 2015: oil's second leg down hits the energy-linked half",
         what=["Q3'15 range $18.90 high → $11.83 low; quarter close $12.83 (−29% QoQ).",
               "WTI fell from ~$60 (June) to below $40 (August); Aug 24, 2015 flash crash."],
         why="Jefferson Terminal and the offshore vessels were pure energy-volume bets. As crude-by-rail economics collapsed, the "
             "market priced the infrastructure side at a loss and sold the stock with MLPs and other yield vehicles."),
    dict(n=3, era="e1", date="2016-02-11", px=8.70, dir="down", move="≈ −43% ($15.27 → $8.65 low)", conf="estimated",
         short="Q3'15 loss + oil at $26",
         title="Q3'15 loss and impairment, then the oil bottom (low $8.65)",
         what=["Q3'15 (Nov 3): net loss −$11.7M (−$0.16/sh), including a $10.5M non-cash impairment on a shipping-container investment.",
               "Infrastructure lost −$8.1M: Jefferson start-up opex, depreciation and terminal-debt interest.",
               "WTI bottomed at ~$26 (Feb 11, 2016). The low of $8.65 meant a ~15% dividend yield."],
         why="The loss showed infrastructure was eating what aviation earned. A 15% yield on an uncut $0.33 quarterly dividend means "
             "the market was pricing a cut. It never came, and the dividend held at $0.33 every quarter through 2019."),
    dict(n=4, era="e1", date="2016-09-30", px=12.51, dir="up", move="≈ +40% ($8.92 → $12.51, mid-2016)", conf="context",
         short="Oil recovers; aviation carries the dividend",
         title="Mid-2016 recovery: oil rebounds and aviation proves it carries the payout",
         what=["Q2'16 low $8.92 → Q3'16 close $12.51 (+36% QoQ).",
               "Q3'16: leasing contributed +$25.8M of funds available for distribution (FAD); infrastructure −$6.0M; corporate −$9.6M.",
               "Oil recovered to $45–50; high-yield demand returned."],
         why="Once crude stabilized, the tail risk on Jefferson shrank. The reported mix showed the aviation book alone covered the "
             "distribution, so the 13–15% yield was mispriced."),
    dict(n=5, era="e1", date="2017-12-29", px=19.90, dir="up", move="≈ +51% ($13.31 → $20.08, 2017)", conf="context",
         short="Steady 2017 re-rating",
         title="2017 grind higher: aviation growth plus the SoftBank–Fortress deal",
         what=["Every quarterly low was above the prior quarter's (10-K price ranges).",
               "SoftBank agreed in Feb 2017 to buy Fortress (FTAI's manager); the management agreement stayed in place.",
               "Long Ridge (Ohio) and Repauno (NJ) were added as infrastructure development projects."],
         why="No single gap. Leasing EBITDA grew quarter after quarter while the 13% yield compressed to ~7%. That re-rating explains "
             "most of the move."),
    dict(n=6, era="e1", date="2018-01-12", px=18.70, dir="down", move="−5.5% offering discount ($19.74 → $18.65)", conf="verified",
         short="Jan-2018 equity raise marks top",
         title="January 2018 follow-on offering marks the top",
         what=["7.0M shares priced at $18.65 vs the $19.74 last sale (Jan 10). ~$128M net.",
               "Fortress also received options on 10% of the shares issued, at the offering price."],
         why="Issuing stock at the high capped the 2017 rally. Holders read it as management treating the stock as a funding "
             "currency for capital-hungry infrastructure projects."),
    dict(n=7, era="e1", date="2018-12-24", px=12.90, dir="down", move="≈ −35% (~$20.0 → ~$12.9, 2018)", conf="estimated",
         short="2018: thin EPS + Q4 crash",
         title="2018 bleed: GAAP earnings didn't cover the dividend, then the Q4 crash",
         what=["2018 GAAP EPS by quarter: −$0.01, $0.01, $0.05, $0.01, against a $1.32 annual dividend.",
               "Q3'18 (Nov 1): management called it 'record adjusted EBITDA', but the stock kept falling.",
               "Dec 4: 1.26M shares sold at $15.83 to an existing holder. Q4: S&P −20%, WTI $76 → $42."],
         why="A yield stock whose payout is not covered by GAAP earnings has no support in a risk-off tape. The December oil and credit "
             "sell-off hit exactly FTAI's holder base. The dividend-adjusted drawdown was −30.2% (Jan 5 → Dec 24)."),
    dict(n=8, era="e1", date="2019-12-31", px=19.50, dir="up", move="≈ +50% (~$12.9 → ~$19.5, 2019)", conf="estimated",
         short="2019 rebound; preferreds not common",
         title="2019 rebound: Fed pivot, better EPS, and preferreds instead of common",
         what=["Q2'19 EPS was $0.24, a big step up from 2018's pennies.",
               "Growth was funded with preferred stock, not common: Series A 8.25% ($86M, Sep) and Series B 8.00% (~$111M net, Nov)."],
         why="The Fed's January 2019 pivot lifted all yield assets. FTAI also stopped diluting common holders and showed earnings "
             "that covered more of the payout, so the stock recovered its 2018 losses."),

    # ======================= ERA 2 =======================
    dict(n=9, era="e2", date="2020-03-18", px=3.69, dir="down", move="≈ −80% (~$18.9 → $3.69 intraday)", conf="verified",
         short="COVID collapse",
         title="COVID: global flying stops; the yield/K-1 holder base liquidates",
         what=["Q4'19 (Feb 27) looked strong: FAD $288.6M, but $167.2M came from one-off infrastructure gains (Long Ridge).",
               "Within three weeks, global passenger traffic fell >90% and ~15,000 aircraft were parked.",
               "Saudi–Russia oil price war at the same time, which hit Jefferson."],
         why="A lessor of mid-life aircraft and engines to weaker airlines faced rent non-payment just as its energy assets lost their "
             "throughput. It also had a leveraged LLC structure owned by yield funds that were forced sellers in the March credit "
             "panic. The stock briefly priced in insolvency."),
    dict(n=10, era="e2", date="2020-06-30", px=15.00, dir="up", move="≈ +300% off the low (to ~$15 by June)", conf="estimated",
         short="Dividend held; deferrals contained",
         title="Recovery: the $0.33 dividend held and lease deferrals stayed contained",
         what=["Q1'20 (Apr 30): FAD $96.0M (aviation $121.3M). Dividend kept at $0.33.",
               "Q2'20: deferrals negotiated on only ~20% of the portfolio (3 months' deferral for 3-month extensions).",
               "Management sized the COVID hit to aviation at ~$20M for Q2."],
         why="The bankruptcy scenario didn't happen. Keeping the dividend was a solvency signal, and contained deferrals meant engines "
             "kept earning. Engine leases are paid on flight hours, and cargo and domestic flying recovered first."),
    dict(n=11, era="e2", date="2020-11-09", px=18.50, dir="up", move="≈ +40% (~$15.5 → ~$22, Oct–Dec 2020)", conf="estimated",
         short="Module Factory deal + vaccine",
         title="The Module Factory is born, then the vaccine rally",
         what=["Oct 22, 2020: partnership with Lockheed Martin's Montreal engine shop to repair CFM56-7B/-5B modules (up to 300 shop visits/yr).",
               "This started 'Aerospace Products': selling refurbished CFM56 modules instead of full shop visits; parts via AAR; PMA parts via a Chromalloy JV.",
               "Nov 9: the Pfizer vaccine announcement lifted all aviation."],
         why="The vaccine drove the move at the time. The Module Factory became the source of FTAI's later ~10x re-rating."),
    dict(n=12, era="e2", date="2021-03-15", px=31.50, dir="up", move="≈ +50% (to $31.81 52-wk high)", conf="estimated",
         short="Reopening trade",
         title="Early-2021 reopening trade peaks at $31.81",
         what=["Cyclical/reopening rotation; 52-week high of $31.81 (exact date unverified, likely Feb–Mar)."],
         why="Macro, not company-specific. Q4'20 results (Feb 25) were weak: net loss −$0.70/sh."),
    dict(n=13, era="e2", date="2021-09-10", px=25.60, dir="down", move="≈ −20% from high (to $25.50 offering)", conf="estimated",
         short="Misses, Transtar, $306M offering",
         title="2021 fade: misses, a $640M railroad buy, and a $306M stock sale",
         what=["Q1'21: EPS −$0.40 vs −$0.34 est.; revenue $77.1M vs $83.2M (−31.6% y/y).",
               "Jun 8: bought U.S. Steel's Transtar railroads for $640M on a $650M bridge loan.",
               "Q2'21: EPS −$0.42 vs −$0.13 est. Sep 9: 12.0M shares sold at $25.50 ($306M) to repay the bridge."],
         why="Aviation still hadn't recovered, yet management doubled down on infrastructure with a bridge-financed acquisition, then "
             "issued stock to pay for it. Each step diluted the aviation story the market was beginning to like."),
    dict(n=14, era="e2", date="2022-04-29", px=17.33, dir="down", move="≈ −35% (~$27 → ~$17, Feb–May 2022)", conf="estimated",
         short="Russia: $195M write-offs",
         title="Russia: aircraft stranded, $195M of charges, a deep EPS miss",
         what=["Feb 24 (invasion day): Q4'21 EPS −$0.19 vs +$0.13 est. Peer AerCap fell −12.7% that week.",
               "Q1'22 (Apr 28): $195M of charges, including a 100% write-off of $125M book value for 12 aircraft and 20 engines stuck in Russia/Ukraine.",
               "Adj. EPS −$1.28 vs −$0.10 est.; revenue $137.8M (−14.6% vs consensus). $290M insurance claims filed. Day move −5.6%."],
         why="Sanctions forced lessors to terminate Russian leases, but the airlines kept the planes. Assets were lost overnight, and "
             "recovery depended on slow, contested insurance claims. The day-one hit was mild only because management guided to "
             "recapturing the $195M via insurance and asset-sale gains."),
    dict(n=15, era="e2", date="2022-08-02", px=19.50, dir="mech", move="−14.5% mechanical (~$22.8 → $19.50)", conf="verified",
         short="FTAI Infrastructure spin (not a loss)",
         title="Spin-off of FTAI Infrastructure (FIP): a mechanical gap, not lost value",
         what=["1 FIP share per FTAI share (record Jul 21, distributed Aug 1). FIP ≈ $3.30 at spin.",
               "Jefferson, Repauno, Long Ridge and Transtar left with FIP. FTAI kept a pure-play aviation business.",
               "Adjusted charts (TradingView, Macrotrends) scale every pre-Aug-2022 price by ~0.855 to remove this gap."],
         why="The quoted price fell by roughly the FIP value delivered to holders. The strategic effect was what mattered: FTAI no "
             "longer carried the infrastructure drag that had held the stock back since the IPO."),
    dict(n=16, era="e2", date="2022-10-27", px=15.00, dir="down", move="≈ −23% ($19.50 → ~$15)", conf="estimated",
         short="Post-spin selling; dividend cut",
         title="Post-spin slide: forced selling, misses, and a dividend cut",
         what=["Q2'22 EPS $0.11 vs $0.20 est. (Adj. EBITDA $165M; Aerospace just $17M).",
               "Q3'22 (Oct 27): EPS $0.33 vs $0.38 est.; revenue $291.1M vs $307.1M. Dividend cut $0.33 → $0.30.",
               "−44.4% YTD on a nominal basis vs S&P 500 −19.6%."],
         why="Infrastructure and yield holders sold the aviation remainder they never wanted. 2022 rate hikes hit lessor valuations, "
             "and the dividend cut (sized to the smaller company) turned away the remaining yield buyers."),
    dict(n=17, era="e2", date="2022-11-11", px=16.50, dir="up", move="≈ +15% (~$15 → ~$17.4 year-end)", conf="estimated",
         short="Becomes a Cayman C-corp (no K-1)",
         title="Conversion to FTAI Aviation Ltd. (Cayman corporation): no more K-1s",
         what=["Merger closed Nov 11, 2022. The LLC became a subsidiary of a regular corporation.",
               "Removed the K-1 tax form that kept many institutions and index funds out."],
         why="The investable universe widened. This was the start of the institutional buyer base that drove 2023–24."),

    # ======================= ERA 3 =======================
    dict(n=18, era="e3", date="2023-02-23", px=24.00, dir="up", move="≈ +40% (Jan–Feb 2023)", conf="estimated",
         short="Q4'22 + 2023 guide",
         title="Q4'22 and the first pure-aviation guide",
         what=["Adj. EBITDA $123.5M (+13% q/q): Leasing $110M, Aerospace $21.7M.",
               "Aerospace had produced ~$91M EBITDA over 5 quarters with zero PMA (non-OEM replacement parts) contribution yet.",
               "2023 guide: leasing EBITDA $350–400M plus ~$100M of asset-sale gains."],
         why="This was the first clean set of numbers without infrastructure. Investors could see a fast-growing, high-margin "
             "aftermarket segment inside what was priced as a mid-life lessor."),
    dict(n=19, era="e3", date="2023-10-31", px=34.50, dir="up", move="+182% for 2023 (≈ $17 → $46)", conf="verified",
         short="Aerospace guide ~doubles for 2024",
         title="2023: Aerospace margins prove out; 2024 guide roughly doubles",
         what=["Q1'23 EPS $0.22 vs $0.41 est. (a miss), but aerospace EBITDA was $27.4M and management called $100M+ for 2023 'very doable'.",
               "Q2'23: Aerospace EBITDA $30.1M at a 44% margin; revenue more than doubled.",
               "Q3'23 (Oct 26): Aerospace $40.6M, 41 modules sold to 11 customers. First 2024 guide: Aerospace $200–250M vs $98M YTD."],
         why="GAAP EPS misses stopped mattering. The market valued Aerospace EBITDA growth and its ~40% margins, which are "
             "aftermarket-parts economics like HEICO or TransDigm, not lessor economics. The Oct guide implied ~2–2.5x growth."),
    dict(n=20, era="e3", date="2024-02-29", px=59.00, dir="up", move="≈ +27% (Jan–Feb 2024)", conf="estimated",
         short="Q4'23: EPS $1.09 vs $0.44",
         title="Q4'23: a big EPS beat and 178 modules for the year",
         what=["Diluted EPS $1.09 vs $0.44 est.; revenue $312.7M in line.",
               "Aerospace Q4 EBITDA $55M; FY23 $160M vs $74M in 2022. 61 modules to 17 customers in Q4; 178 to 30 in 2023."],
         why="The customer count was the key number. Thirty airlines and MROs were buying modules, so this was no longer a few "
             "one-off trades but a repeatable product with a widening customer base."),
    dict(n=21, era="e3", date="2024-05-31", px=85.00, dir="up", move="≈ +20% (May 2024)", conf="estimated",
         short="Internalization + Montreal plant",
         title="Fortress fired, the factory bought",
         what=["May 28: internalized management, ending the Fortress agreement for $150M cash + 1.87M shares (≈ $300M). ~$30M/yr savings.",
               "May 30: bought Lockheed Martin's Montreal engine shop for $170M (526k sq ft, up to 900 CFM56 modules/yr, 3 test cells).",
               "Fortress sold 2.09M shares in a secondary at $80.42 (no proceeds to FTAI)."],
         why="This removed the governance discount from the IPO (no more fees or 10% options on raises). It also gave FTAI ownership "
             "of the capacity behind its main growth engine. Russell 1000 promotion in late June added index demand."),
    dict(n=22, era="e3", date="2024-07-31", px=112.00, dir="up", move="to ATH $124.4 by Aug", conf="estimated",
         short="Q2'24: aero guide raised to $325–350M",
         title="Q2'24: a GAAP loss the market ignored; aerospace guide raised 35%",
         what=["Revenue $443.6M, 27% above consensus.",
               "GAAP EPS −$2.26 vs +$0.32 est., entirely the one-time ~$300M internalization fee plus a $13.9M debt-extinguishment loss.",
               "Aerospace EBITDA $91.2M (37% margin). FY24 aerospace guide raised ~$250M → $325–350M. 20 V2500 engines inducted YTD."],
         why="A non-cash/one-time loss, a revenue blowout, and a third guide raise. The V2500 (A320ceo engine) induction showed a "
             "second product line beyond CFM56."),
    dict(n=23, era="e3", date="2024-10-31", px=129.50, dir="down", move="−11.1% intraday (≈ $145 → $129)", conf="verified",
         short="Q3'24: beat but low-quality, less disclosure",
         title="Q3'24: a headline beat sold for its quality",
         what=["Revenue $465.8M vs $422.5M est.; Adj. EBITDA $232.0M vs $214.6M; EPS $0.76 vs $0.77. FY aerospace guide raised to $360–375M.",
               "Leasing EBITDA $136.4M included $14.3M of gains on asset sales.",
               "Management stopped disclosing module unit counts, citing competition. Aerospace margin slipped to 34% from 37%."],
         why="The beat was partly asset sales, which are one-time and lower quality. Removing the module count took away the market's "
             "main volume check right when the bull case relied on it. Analysts also asked whether module demand would last once "
             "OEM supply chains normalize. After a ~3x run, those quality questions outweighed the beat."),
    dict(n=24, era="e3", date="2024-11-21", px=174.00, dir="up", move="+8.4% Nov 1, +7% Nov 6 → ATH $174", conf="verified",
         short="PMA approval + election",
         title="Second PMA part approved, then the election rally, to an all-time high",
         what=["Nov 1: FAA approved Chromalloy's CFM56-5B/7B HPT stage-1 vane, the 2nd of 5 planned PMA parts for the FTAI JV. +8.4%.",
               "Benchmark PT $300 ('rocket fuel' for the Module Factory); Barclays PT $110 → $135.",
               "Nov 6: post-election industrials rally +7%. Closing ATH $174.00 on Nov 21 (intraday $181.64)."],
         why="PMA parts let FTAI replace expensive OEM parts at a fraction of the cost. That is the main lever on module margins and "
             "answered the 'margin slipping' worry within 48 hours."),
    dict(n=25, era="e3", date="2024-12-30", px=126.60, dir="down", move="≈ −27% ($174 → ~$127)", conf="estimated",
         short="December de-rating (no co. news)",
         title="December 2024 drawdown with no company news",
         what=["No company-specific catalyst found.",
               "Profit-taking after a ~3.5x year, plus the broad sell-off after the hawkish Dec 18 Fed meeting (unverified)."],
         why="A crowded momentum winner gave back gains in a risk-off month. This is context, not a sourced cause."),
    dict(n=26, era="e3", date="2024-12-31", px=144.04, dir="up", move="+13.8% (≈ $126.6 → $144.04)", conf="verified",
         short="Strategic Capital Initiative + 2025 guide",
         title="Strategic Capital Initiative (SCI) and a 2025 guide above consensus",
         what=["SCI: third-party partnerships buy on-lease 737NG/A320ceo aircraft ($3B+/yr capacity). FTAI sells the first 46 aircraft for ~$549M.",
               "Every SCI engine is maintained exclusively through FTAI's module/engine exchange: ~$200M incremental aerospace EBITDA by 2026 (analysts).",
               "2025 guide: $1.1–1.15B segment EBITDA (Aerospace $600–650M), midpoint ~5% above the $1.075B consensus."],
         why="SCI turns the capital-heavy lessor into an asset-light manager whose owned fleet becomes a captive customer for "
             "high-margin modules. That case for MRO-style multiples, plus a guide above Street, reversed half the December slide in one session."),

    # ======================= ERA 4 =======================
    dict(n=27, era="e4", date="2025-01-15", px=116.08, dir="down", move="−24% ($153.29 → $116.08)", conf="verified",
         short="Muddy Waters short report",
         title="Muddy Waters: 'the aftermarket business is mostly selling engines'",
         what=["Claims: Aerospace Products books one-off whole-engine sales as if they were module/MRO revenue.",
               "~80% of Aerospace EBITDA is gains on sale. Channel stuffing flattered 2023.",
               "Leasing over-depreciates assets before transferring them to Aerospace at a low book value, inflating its margins. Insiders were selling."],
         why="The whole re-rating depended on Aerospace earnings being recurring and high-margin. The report argued that margin came "
             "from accounting transfers between segments. CEO Joe Adams called it 'baseless and nonsensical' and said depreciation "
             "policy had been unchanged since 2015. Benchmark and Morgan Stanley defended the company."),
    dict(n=28, era="e4", date="2025-01-21", px=88.00, dir="down", move="−23% gap ($112.38 → $86.37 open)", conf="verified",
         short="Audit Committee review; 10-K risk",
         title="Audit Committee opens an independent review; the 10-K might be late",
         what=["Jan 18: the Audit Committee hired independent legal and forensic-accounting advisors to review the allegations.",
               "FTAI warned that its 10-K could be delayed.",
               "Jan 29: a second short seller, Snowcap, called Aerospace 'an elaborate fabrication', saying ~50% of profit was repackaged COVID gains and inventories were overvalued. −10%."],
         why="A forensic review plus a possibly late 10-K is how accounting blow-ups start. Funds with governance mandates had to sell "
             "first and ask questions later. January ended down ~30%, with an intraday low near $75."),
    dict(n=29, era="e4", date="2025-02-20", px=127.60, dir="up", move="+13.9% (+16% pre-market)", conf="verified",
         short="Review: allegations 'without merit'",
         title="Review clears FTAI; 10-K to be filed on time",
         what=["The Audit Committee concluded the short-seller allegations were 'without merit'.",
               "Q4'24 (Feb 26): Adj. EBITDA $252M vs $240M est. (beat); EPS $0.84 vs $0.89 (miss). FY24 Aerospace net income +92%. About −5% the next day.",
               "Mar 3: Muddy Waters' second report alleged FTAI modules turned up at an Iranian MRO (a possible sanctions breach). −5%."],
         why="The tail risk (restatement, delisting) was removed in one press release, and February finished +28%. The follow-up "
             "allegations moved the stock only ~5% each, because the market had already discounted the short sellers' credibility."),
    dict(n=30, era="e4", date="2025-04-08", px=81.50, dir="down", move="≈ −37% (~$129 → ~$81)", conf="estimated",
         short="Tariff sell-off",
         title="Tariff shock: an air-travel recession scare",
         what=["March −13.7%, April −3.5%; intraday low near $81 around 'Liberation Day' (April 2–8).",
               "+5.3% bounce when EU tariffs were postponed."],
         why="Tariffs raised the odds of a recession, which means fewer flight hours, fewer shop visits and weaker lessees. The stock "
             "had also just been through a governance scare, so its holder base was nervous."),
    dict(n=31, era="e4", date="2025-05-01", px=91.36, dir="down", move="−14.8% (≈ $107 → $91.36)", conf="verified",
         short="Q1'25 miss: margins + fewer asset sales",
         title="Q1'25: a narrow miss on the wrong lines",
         what=["EPS $0.87 vs $0.95; revenue $502.1M vs $504.8M.",
               "Aerospace EBITDA $131M at a 36% margin, down from ~40%. Asset-sale gains came in lighter than modeled, so leasing fell short.",
               "SCI: 98 aircraft owned or under LOI; >$4B 2025 deployment; $2.5B facility with Apollo's ATLAS and Deutsche Bank."],
         why="Weeks after a short report attacking Aerospace margins and gains-on-sale, both lines disappointed. Investors read it as "
             "partial confirmation of the bear case and sold. RBC cut its target; Stifel upgraded on the dip."),
    dict(n=32, era="e4", date="2025-07-30", px=139.50, dir="up", move="+14.3%", conf="verified",
         short="Q2'25 blowout: 184 modules",
         title="Q2'25: a clean beat on every line",
         what=["EPS $1.57 vs ~$1.30; revenue $676.2M vs ~$575M; Adj. EBITDA $347.8M vs $288.7M.",
               "Aerospace revenue $420.7M; EBITDA $164.9M (~39% margin, +81% y/y). 184 CFM56 modules (+33% q/q).",
               "Adjusted free cash flow >$400M in the quarter."],
         why="This answered the short thesis with cash. Record module volume, a restored margin, and $400M of free cash flow are hard "
             "to produce with accounting transfers. The stock rose from ~$91 in May to ~$167 by September."),
    dict(n=33, era="e4", date="2025-10-28", px=175.00, dir="up", move="≈ +2% (EPS miss shrugged off)", conf="verified",
         short="Q3'25: miss, but 2026 guide $1.525B",
         title="Q3'25: an EPS miss offset by the first 2026 guide",
         what=["EPS $1.10 vs $1.21 est. (−9%). Revenue $667.1M in line. Aerospace EBITDA $180.4M (35%, +77% y/y).",
               "SCI closed $2B of equity; deployment target >$6B. FTAI co-invests ~$380M for 19%. Dividend raised $0.30 → $0.35.",
               "First 2026 guide: Aerospace $1.0B, Leasing $525M, total $1.525B; ~$1B adjusted FCF."],
         why="A $1B Aerospace target for 2026 and a dividend raise mattered more than an 11-cent miss. Not a 7% mover, but it set "
             "the bar for 2026."),
    dict(n=34, era="e4", date="2025-12-30", px=197.00, dir="up", move="+12–14% (to $199.88 intraday)", conf="verified",
         short="FTAI Power: CFM56 → data-center turbines",
         title="FTAI Power: CFM56 engines become 25MW turbines for AI data centers",
         what=["Converts CFM56 cores into 25MW aeroderivative gas turbines for data-center power. Production starts 2026, scaling to 100+ units/yr.",
               "Jefferies estimated >$750M EBITDA/yr at full run-rate (≈$20M+ per unit)."],
         why="It linked FTAI's engine inventory to the AI-power shortage, the most richly valued theme in the market. It also gave a "
             "second use for retiring CFM56 engines, answering the 'what happens when the fleet ages out' question. 2025 ended +36.7%."),

    # ======================= ERA 5 =======================
    dict(n=35, era="e5", date="2026-01-28", px=290.00, dir="up", move="+38% in January (52-wk high $293.49)", conf="verified",
         short="Power + Palantir + CFM agreement",
         title="January 2026: power hype plus an OEM truce",
         what=["Momentum from FTAI Power; a multi-year Palantir AI-platform partnership (announced Nov 2025).",
               "Late January: a multi-year agreement with CFM International (GE/Safran) covering CFM56 parts and support."],
         why="The CFM deal mattered most. A long-term bear risk was that GE/Safran would squeeze an aftermarket competitor through parts "
             "supply. A formal agreement with the OEM reduced that risk, just as the power story was expanding the valuation."),
    dict(n=36, era="e5", date="2026-02-26", px=295.00, dir="down", move="−3.6% pre-market (muted)", conf="verified",
         short="Q4'25: EPS miss, guide raised",
         title="Q4'25: second EPS miss in a row, offset by a guide raise",
         what=["EPS $1.08 vs $1.25 (−13.6%); Adj. EBITDA $277.2M also below consensus.",
               "FY25 Aerospace EBITDA $671.3M (+76%). 2026 guide raised $100M to $1.525–1.625B (Aerospace $1.05B, Leasing $575M).",
               "Dividend → $0.40. Mod-1 turbine due Q4'26; 100 units planned for 2027."],
         why="At ~$300, investors were paying for 2027 power units, so a quarterly miss was easy to look past. The pattern of misses "
             "was building, though."),
    dict(n=37, era="e5", date="2026-04-29", px=213.00, dir="down", move="≈ −30% (~$302 → ~$213)", conf="estimated",
         short="Iran war: Brent > $100",
         title="Iran war: Brent above $100 and stagflation fears",
         what=["Conflict disrupted the Strait of Hormuz; Brent above $100.",
               "Q4'25 GDP revised to 0.7%. Risk-off across aviation."],
         why="Jet fuel is airlines' biggest cost. A spike squeezes lessee credit and leads airlines to park older, thirstier planes, "
             "which are exactly the 737NG/A320ceo fleet FTAI serves. Fewer flight hours means fewer shop visits."),
    dict(n=38, era="e5", date="2026-04-30", px=249.60, dir="up", move="+17.2%", conf="verified",
         short="Q1'26: revenue +65%, volume over margin",
         title="Q1'26: margins sacrificed for volume, and the market approved",
         what=["Revenue $830.7M vs $741M (+12% beat, +65% y/y). EPS $1.29 vs $1.54, the third straight miss.",
               "Aerospace revenue $743.8M (+104%), EBITDA $222.6M, margin ~30% vs ~35–39% before. 270 modules vs 138 a year ago.",
               "Dividend → $0.45. Power partnership with China's Jereh Group disclosed."],
         why="Management said it was deliberately trading margin for share: bigger airline programs and more full-restoration work. "
             "After a 30% drawdown, doubling module volume and a credible power partner outweighed the margin dilution, for now."),
    dict(n=39, era="e5", date="2026-07-22", px=238.00, dir="up", move="+5.6–8% Jul 22 (after −7% Jul 8)", conf="verified",
         short="Downgrades; $1.465B turbine order",
         title="July: downgrades, then a $1.465B turbine order",
         what=["Jul 8: −7% on downgrades to Hold (Zacks, Weiss) plus fuel and risk-off worries.",
               "Jul 22: J&F Power Systems (the FTAI–Jereh JV) signed a 5-year supply deal with a large cloud provider. First order $1.465B of Mod-1 gen-sets through Nov 2027.",
               "Compass Point estimated $280–350M+ of EBITDA from the contract."],
         why="The order was hard proof that the power business existed, but it only briefly interrupted a slide. The stock was down "
             "~25% over 30 days going into the print."),
    dict(n=40, era="e5", date="2026-07-30", px=197.50, dir="down", move="−7.1% Jul 29; −19% after hours, closed flat", conf="verified",
         short="Q2'26: miss, leasing guide cut",
         title="Q2'26: margin reset and leasing guidance cut",
         what=["Revenue $953.1M (+41%, beat). EPS $1.13 vs ~$1.35–1.68 (fourth straight miss); Adj. EBITDA $291.4M vs $318.9M.",
               "Aerospace $249.7M at a 29% margin. Management now guides ~30% for the next 1–2 years.",
               "Leasing EBITDA $88.2M vs $199.3M a year earlier as aircraft moved into SCI. 2026 leasing guide cut $575M → $475M. Module target raised 1,050 → 1,200."],
         why="Two things broke: (1) ~30% Aerospace margins are now the plan, not a dip, so the 'HEICO-like 40%' multiple no longer fits; "
             "(2) SCI shifts leasing EBITDA off FTAI's books faster than modeled. It fell 19% after hours but closed flat once buyers saw "
             "record revenue and module volume."),
    dict(n=41, era="e5", date="2026-09-28", px=167.10, dir="down", move="≈ −26% ($226.66 → $167.10)", conf="estimated",
         short="Aug–Sep slide; $500M buyback",
         title="August–September slide despite a $500M buyback",
         what=["Aug 12 $226.66 → Sep 28 $167.10; no single company-specific catalyst confirmed.",
               "Sep 15: $500M buyback authorized through Sep 2029, +5.6% that day, then faded.",
               "Grouped in sell-off coverage with Sterling, Herc and other AI-infrastructure names (possible theme de-rating)."],
         why="With margins guided lower and power revenue still mostly a 2027 story, the stock traded as a crowded AI-power proxy. "
             "It fell as that theme cooled. Latest available close: $167.10, ~45% below the February peak."),
]
